---
# tasks file for dns-record
- name: Create dns record
  win_dns_record:
    name: "{{ record_name }}"
    type: "{{ record_type }}"
    value: "{{ record_value }}"
    zone: "{{ record_zone }}"
  when: (action == "Create") or (action == "create")

- name: Remove dns record
  win_dns_record:
    name: "{{ record_name }}"
    type: "{{ record_type }}"
    state: "absent"
    zone: "{{ record_zone }}"
  when: (action == "Remove") or (action == "remove")
